/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/logo-bueno.glb -o src/components/logo.jsx -r public -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Logo(props) {
  const { nodes, materials } = useGLTF('/models/logo-bueno.glb')
  const logoRef = useRef()

  useFrame(() => {
    logoRef.current.rotation.y += 0.005
  })

  return (
    <group {...props} ref={logoRef} dispose={null} >
      <mesh name="curve-4" geometry={nodes['curve-4'].geometry} material={nodes['curve-4'].material} />
      <mesh name="curve-3" geometry={nodes['curve-3'].geometry} material={nodes['curve-3'].material} />
      <mesh name="curve-2" geometry={nodes['curve-2'].geometry} material={nodes['curve-2'].material} />
      <mesh name="curve-1" geometry={nodes['curve-1'].geometry} material={nodes['curve-1'].material} />
      <mesh name="letter-23" geometry={nodes['letter-23'].geometry} material={nodes['letter-23'].material} />
      <mesh name="letter-22" geometry={nodes['letter-22'].geometry} material={nodes['letter-22'].material} />
      <mesh name="letter-21" geometry={nodes['letter-21'].geometry} material={nodes['letter-21'].material} />
      <mesh name="letter-20" geometry={nodes['letter-20'].geometry} material={nodes['letter-20'].material} />
      <mesh name="letter-19" geometry={nodes['letter-19'].geometry} material={nodes['letter-19'].material} />
      <mesh name="letter-18" geometry={nodes['letter-18'].geometry} material={nodes['letter-18'].material} />
      <mesh name="letter-17" geometry={nodes['letter-17'].geometry} material={nodes['letter-17'].material} />
      <mesh name="letter-16" geometry={nodes['letter-16'].geometry} material={nodes['letter-16'].material} />
      <mesh name="letter-15" geometry={nodes['letter-15'].geometry} material={nodes['letter-15'].material} />
      <mesh name="letter-14" geometry={nodes['letter-14'].geometry} material={nodes['letter-14'].material} />
      <mesh name="letter-13" geometry={nodes['letter-13'].geometry} material={nodes['letter-13'].material} />
      <mesh name="letter-12" geometry={nodes['letter-12'].geometry} material={nodes['letter-12'].material} />
      <mesh name="letter-11" geometry={nodes['letter-11'].geometry} material={nodes['letter-11'].material} />
      <mesh name="letter-10" geometry={nodes['letter-10'].geometry} material={nodes['letter-10'].material} />
      <mesh name="letter-9" geometry={nodes['letter-9'].geometry} material={nodes['letter-9'].material} />
      <mesh name="letter-8" geometry={nodes['letter-8'].geometry} material={nodes['letter-8'].material} />
      <mesh name="letter-7" geometry={nodes['letter-7'].geometry} material={nodes['letter-7'].material} />
      <mesh name="letter-6" geometry={nodes['letter-6'].geometry} material={nodes['letter-6'].material} />
      <mesh name="letter-5" geometry={nodes['letter-5'].geometry} material={nodes['letter-5'].material} />
      <mesh name="letter-4" geometry={nodes['letter-4'].geometry} material={nodes['letter-4'].material} />
      <mesh name="letter-3" geometry={nodes['letter-3'].geometry} material={nodes['letter-3'].material} />
      <mesh name="letter-2" geometry={nodes['letter-2'].geometry} material={nodes['letter-2'].material} />
      <mesh name="letter-1" geometry={nodes['letter-1'].geometry} material={nodes['letter-1'].material} />
      <mesh name="screen-border" geometry={nodes['screen-border'].geometry} material={nodes['screen-border'].material} />
      <mesh name="screen-content" geometry={nodes['screen-content'].geometry} material={nodes['screen-content'].material} />
      <mesh name="cubes-color-13" geometry={nodes['cubes-color-13'].geometry} material={nodes['cubes-color-13'].material} />
      <mesh name="cubes-color-12" geometry={nodes['cubes-color-12'].geometry} material={nodes['cubes-color-12'].material} />
      <mesh name="cubes-color-11" geometry={nodes['cubes-color-11'].geometry} material={nodes['cubes-color-11'].material} />
      <mesh name="cubes-color-10" geometry={nodes['cubes-color-10'].geometry} material={nodes['cubes-color-10'].material} />
      <mesh name="cubes-color-9" geometry={nodes['cubes-color-9'].geometry} material={nodes['cubes-color-9'].material} />
      <mesh name="cubes-color-8" geometry={nodes['cubes-color-8'].geometry} material={nodes['cubes-color-8'].material} />
      <mesh name="cubes-color-7" geometry={nodes['cubes-color-7'].geometry} material={nodes['cubes-color-7'].material} />
      <mesh name="cubes-color-6" geometry={nodes['cubes-color-6'].geometry} material={nodes['cubes-color-6'].material} />
      <mesh name="cubes-color-5" geometry={nodes['cubes-color-5'].geometry} material={nodes['cubes-color-5'].material} />
      <mesh name="cubes-color-4" geometry={nodes['cubes-color-4'].geometry} material={nodes['cubes-color-4'].material} />
      <mesh name="cubes-color-3" geometry={nodes['cubes-color-3'].geometry} material={nodes['cubes-color-3'].material} />
      <mesh name="cubes-color-2" geometry={nodes['cubes-color-2'].geometry} material={nodes['cubes-color-2'].material} />
      <mesh name="cubes-color-1" geometry={nodes['cubes-color-1'].geometry} material={nodes['cubes-color-1'].material} />
      <mesh name="polygone-stand" geometry={nodes['polygone-stand'].geometry} material={nodes['polygone-stand'].material} />
      <mesh name="rectangle-stand" geometry={nodes['rectangle-stand'].geometry} material={nodes['rectangle-stand'].material} />
    </group>
  )
}

useGLTF.preload('/models/logo-bueno.glb')
